[docker] Update GCC and Conan version
conan-io/training pull request #97
Opened 2022-05-19 15:40 UTC by uilianries

- Use docker image `conanio/gcc11-ubuntu16.04:1.48.1`
- Update from GCC7 to GCC11
- Update from Conan 1.43.1 to 1.48.1

2022-05-23 15:06 UTC, memsharded approved these changes

2022-05-23 16:16 UTC, uilianries commented
@memsharded All good now. We can check the exercise status directly from CI.

Please, note that I updated more things (all listed in PR description)

For now is running on my fork, but after merging it, it will run here too.

Current current is good: https://github.com/uilianries/conan-training/runs/6558999851?check_suite_focus=true

2022-05-23 17:00 UTC, memsharded reviewed
Looking good, just one question regarding zlib version

2022-05-23 18:24 UTC, uilianries commented on catchup.sh
> +    conan search zlib/1.2.12@
Yes, it's possible. Let me some tests, because some them want 1.2.12, I guess they want the latest version available.

2022-05-23 18:30 UTC, uilianries commented on catchup.sh
> +    conan search zlib/1.2.12@
Now I get. We install Boost, which is updated now and will required 1.2.12. I'll keep 1.2.11 and only update those tests.

2022-05-23 18:50 UTC, uilianries commented
Downgraded to GCC10 after some tests. The profile expected for Boost 1.72.0 is not available with GCC11 (it's expected as we avoid building old package versions).

Zlib will be 1.2.12 in some cases, but when it's a dependency, not the main package.

https://github.com/uilianries/conan-training/runs/6561117002?check_suite_focus=true

2022-05-23 20:43 UTC, memsharded requested changes
Need to clean the changes from running the exercises

2022-05-23 20:43 UTC, memsharded commented on consumer/CMakeLists.txt
> +target_link_libraries(timer CONAN_PKG::poco CONAN_PKG::hello
This is not right, it shouldn't require here the ``CONAN_PKG::hello``

2022-05-23 20:43 UTC, memsharded commented on consumer/conanfile.txt
> +hello/0.1@user/testing
It seems you are committing the changes after running the exercise.

2022-05-23 20:43 UTC, memsharded commented on consumer/timer.cpp
> +#include "hello.h"
Same, avoid these changes, they are the exercise

2022-05-23 20:43 UTC, memsharded commented on gtest/hello/conanfile.py
> +    build_requires =  "gtest/1.8.1"
Avoid this change, this is the result of the exercise

2022-05-23 20:43 UTC, memsharded commented on lockfiles/hello/src/hello.cpp
> +    std::cout << "Hello World **** 0.2 **** Release!" <<std::endl;
Same

2022-05-23 20:43 UTC, memsharded commented on package_id/hello/src/hello.h
> +    std::cout << "Hello World **** 1.1 **** Release!" <<std::endl;
Same

2022-05-23 20:43 UTC, memsharded commented on myconfig/hooks/check_name.py
> +    if '-' in ref:
Same

2022-05-23 20:43 UTC, memsharded commented on requires_conflict/conanfile.txt
> +zlib/1.2.11
Same

2022-05-24 07:21 UTC, uilianries commented
The curse of git --all ... I gonna revert those changes, sorry.

2022-05-24 07:24 UTC, uilianries commented on docker_environment/docker-compose.yml
> +version: "3.5"
It changed from CRLF to LF. It's hard to review, but only `CONAN_VERSION: ${CONAN_VERSION}` and `ARTIFACTORY_VERSION: ${ARTIFACTORY_VERSION}` have been added. The advantage is we can parametrize both versions to run locally or for future update.

2022-05-24 09:15 UTC, uilianries commented
Good to go! 

The tests now are running into the training docker image.

https://github.com/uilianries/conan-training/runs/6570231090?check_suite_focus=true

2022-05-24 13:22 UTC, memsharded approved these changes

2022-05-24 13:22 UTC, merged

2022-05-24 13:33 UTC, memsharded commented
Added some notes in the Academy course, hopefully those comments will avoid some support questions